# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fda28e42f0265a24b4375d72108f50c07dfe545e969af76d4e5d7e4d5b5483ca765c6e3918891ed0fe7ea70e33813510e855786e2d887984e5712899a010074

test:
  secret_key_base: 84bc29cbe6f54be09c12c6533014c67d28a7f265fb5d3237af1cd8a95dc31829bfcac7765be1036fd1fbb0c2fb5e66c07357d22190bac18ca130c630c4792f31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
